version: '2'

services:
  nginx:
    image: nginx:alpine
    restart: always
    links:
      - fpm5-6-23
      - fpm7-0-8
    ports:
      - "80:80"
    volumes:
      - ./nginx/enabled:/etc/nginx/conf.d
      - ./nginx/snippets:/nginx/snippets
    volumes_from:
      - data

  fpm5-6-23:
    image: php:5.6.23-fpm-alpine
    restart: always
    volumes_from:
      - data

  fpm7-0-8:
    image: php:7.0.8-fpm-alpine
    restart: always
    volumes_from:
      - data

  db:
    image: harianto/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/storage:/var/lib/mysql

  dbadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"

  # docker-node:
  #   image: harianto/api-sylo-space
  #   restart: always
  #   volumes:
  #     - ./node_vhosts/docker.node/data:/home/node/app/src/data
  #   volumes_from:
  #     - data

  data:
    image: alpine:latest
    command: /bin/sh
    volumes:
      - ./vhosts:/vhosts
      - ./tmp:/tmp

