version: '2'

services:
  nginx:
    image: nginx:alpine
    links:
      - fpm5-6-23
      - fpm7-0-8
    ports:
      - "80:80"
    volumes:
      - ./nginx/enabled:/etc/nginx/conf.d
      - ./nginx/snippets:/nginx/snippets
    volumes_from:
      - data

  fpm5-6-23:
    image: php:5.6.23-fpm-alpine
    volumes_from:
      - data

  fpm7-0-8:
    image: php:7.0.8-fpm-alpine
    volumes_from:
      - data

  db:
    image: harianto/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/storage:/var/lib/mysql

  dbadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"

  data:
    image: alpine:latest
    command: /bin/sh
    volumes:
      - ./vhosts:/vhosts
      - ./tmp:/tmp

